#ifndef PORT_H
#define PORT_H

#define ENTER_CRITICAL_SECTION()
#define EXIT_CRITICAL_SECTION()

#ifndef RTCOS_MAX_TASKS_COUNT
#define RTCOS_MAX_TASKS_COUNT                    2
#endif /* RTCOS_MAX_TASKS_COUNT */

#ifndef RTCOS_MAX_FUTURE_EVENTS_COUNT
#define RTCOS_MAX_FUTURE_EVENTS_COUNT            2
#endif /* RTCOS_MAX_FUTURE_EVENTS_COUNT */

#ifndef RTCOS_MAX_MESSAGES_COUNT
#define RTCOS_MAX_MESSAGES_COUNT                 2
#endif /* RTCOS_MAX_MESSAGES_COUNT */

#ifndef RTCOS_MAX_TIMERS_COUNT
#define RTCOS_MAX_TIMERS_COUNT                   2
#endif /* RTCOS_MAX_TIMERS_COUNT */

#endif /* PORT_H */
