name: Build

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Clone repo with its submodules
    - uses: actions/checkout@v2
      with:
        submodules: true

    # Install python
    - name: Set up Python
      uses: actions/setup-python@v2

    # Install PlatformIO
    - name: Set up platformio
      run: |
        cd examples/arduino
        python -m pip install --upgrade pip
        pip install platformio

    # Buil the firmware
    - name: Build Firmware
      run: |
        cd examples/arduino
        pio run

    # Check the firmware
    - name: Check Firmware
      run: |
        cd examples/arduino
        pio check

    # Generate doxygene documentation
    - name: Generate documentation
      uses: mattnotmitt/doxygen-action@v1
      with:
          working-directory: '.'
          doxyfile-path: 'docs/rtcos_doxyfile'
