name: Build

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Clone repo with its submodules
    - uses: actions/checkout@v2
      with:
        submodules: true

    # Install python
    - name: Set up Python
      uses: actions/setup-python@v2

    # Install PlatformIO
    - name: Set up platformio
      run: |
        cd examples/arduino
        python -m pip install --upgrade pip
        pip install platformio

    # Build the arduino example firmware
    - name: Build Firmware
      run: |
        cd examples/arduino
        pio run

    # Build the stm32 example firmware
    - name: Build Firmware
      run: |
        cd examples/stm32
        pio run
